### ISSUE TITLE
npm build is failing

### ISSUE THREAD

**Issue by donalmurtagh** [json-schema-form/json-schema-form-core#6]
when I run `npm run build` it fails due to the following error:

```
json-schema-form-core$ npm run build

> json-schema-form-core@1.0.0-alpha.4 build /Users/dmurtagh/workspace/examples/asf/json-schema-form-core
> webpack

/Users/dmurtagh/workspace/examples/asf/json-schema-form-core/webpack.config.js:22
let library = 'JSONSchemaFormCore';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/Users/dmurtagh/workspace/examples/asf/json-schema-form-core/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/dmurtagh/workspace/examples/asf/json-schema-form-core/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
```

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
I merged the PR, but isn't const also requiring strict mode? Not sure why it was working on my machine at home, unless I'd fixed it but didn't commit the fix yet... either way glad to have you in the contributor list! :)
